### ISSUE TITLE
DNS record update

### ISSUE THREAD

**Issue by asafs133** [lmammino/godaddy-dns#13]
Hi,

I didn't understand where should I need to add the new value to be updated.
For example, Let's say that this is my configuration file content:
{
  "apiKey": "some_api_key_values",
  "secret": ""some_secret_values,
  "domain": "mydomain.com",
  "records": [{"type": "CNAME", "name": "mysubdomain", "ttl": 600}]
}

I want to update the CNAME value (which means destination value) and I didn't find where should I add it.
If you could share with me a full configuration file it would be better.
Please help.

Thanks.

**Comment by lmammino** [comment]
Hello @asafs133,
first of all thanks for adopting this project and for raising an issue here (please, if you like the software remember to give it a star 😇).

Regarding your question,
this tool doesn't make much sense to be used with CNAME records.
The only goal of the tool (for what concerns the current implementation) is to update the IP of an A type record with the current public IP of the machines that updates the record.

The classic use case is when you have a web server (or another public service) on a machine that can change its public IP and you want to update your DNS entry every time it happens.

CNAMEs are generally used as aliases, so you shouldn't generally need to trigger a change if your ip changes...

Let me know if this answer makes sense to you!

**Comment by lmammino** [comment]
Closing this for now. Feel free to re-open it if you still have questions related to this issue
