### ISSUE TITLE
Usage failure

### ISSUE THREAD

**Issue by russellhoff** [lmammino/godaddy-dns#21]
After installing godaddy-dns, I can't execute it. I typed:
`$ sudo npm install -g godaddy-dns`
/usr/local/bin/godaddy-dns -> /usr/local/lib/node_modules/godaddy-dns/godaddy-dns.
/usr/local/lib
└─┬ godaddy-dns@1.1.0
  ├── commander@2.12.2
  └─┬ request@2.83.0
    ├── aws-sign2@0.7.0
    ├── aws4@1.6.0
    ├── caseless@0.12.0
    ├─┬ combined-stream@1.0.5
    │ └── delayed-stream@1.0.0
    ├── extend@3.0.1
    ├── forever-agent@0.6.1
    ├─┬ form-data@2.3.1
    │ └── asynckit@0.4.0
    ├─┬ har-validator@5.0.3
    │ ├─┬ ajv@5.5.0
    │ │ ├── co@4.6.0
    │ │ ├── fast-deep-equal@1.0.0
    │ │ ├── fast-json-stable-stringify@2.0.0
    │ │ └── json-schema-traverse@0.3.1
    │ └── har-schema@2.0.0
    ├─┬ hawk@6.0.2
    │ ├── boom@4.3.1
    │ ├─┬ cryptiles@3.1.2
    │ │ └── boom@5.2.0
    │ ├── hoek@4.2.0
    │ └── sntp@2.1.0
    ├─┬ http-signature@1.2.0
    │ ├── assert-plus@1.0.0
    │ ├─┬ jsprim@1.4.1
    │ │ ├── extsprintf@1.3.0
    │ │ ├── json-schema@0.2.3
    │ │ └─┬ verror@1.10.0
    │ │   └── core-util-is@1.0.2
    │ └─┬ sshpk@1.13.1
    │   ├── asn1@0.2.3
    │   ├── bcrypt-pbkdf@1.0.1
    │   ├── dashdash@1.14.1
    │   ├── ecc-jsbn@0.1.1
    │   ├── getpass@0.1.7
    │   ├── jsbn@0.1.1
    │   └── tweetnacl@0.14.5
    ├── is-typedarray@1.0.0
    ├── isstream@0.1.2
    ├── json-stringify-safe@5.0.1
    ├─┬ mime-types@2.1.17
    │ └── mime-db@1.30.0
    ├── oauth-sign@0.8.2
    ├── performance-now@2.1.0
    ├── qs@6.5.1
    ├── safe-buffer@5.1.1
    ├── stringstream@0.0.5
    ├─┬ tough-cookie@2.3.3
    │ └── punycode@1.4.1
    ├── tunnel-agent@0.6.0
    └── uuid@3.1.0

Then, I run `$ godaddy-dns -V` returning the following exception:
`module.js:471
    throw err;
    ^

Error: Cannot find module 'request-promise'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/godaddy-dns/godaddy-dns.js:9:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)`

How can I solve it?

Installed NodeJS version is `v6.11.4` and NPM's `3.5.2`. I'm running Ubuntu 17.10 Desktop 64 bit.

Thanks.

**Comment by lmammino** [comment]
Oops i accidentally moved it in the dev dependencies during the last update. I will address it later this evening, but feel free to submit a PR if you have time.

Thanks for reporting the issue

**Comment by russellhoff** [comment]
Thanks for your fast reply. I'm new to NodeJS and never coded before. Anyway, I'll try it.

**Comment by russellhoff** [comment]
Should I move only `"request-promise": "^4.2.2"` from devDependencies to dependencies? What else and/or versions should I write into dependencies?

Thanks

**Comment by lmammino** [comment]
That's right, if you can also change the version of the package (the one at
the top) to be "1.1.1" in your PR i should be able to approve it directly
from my mobile. The CI should take care of publishing the new version then
😉

Thanks

**Comment by russellhoff** [comment]
done!

**Comment by lmammino** [comment]
Thanks a million. New version Just released. Let me know if notte works as expected.

**Comment by russellhoff** [comment]
Working! Thanks a lot to you.

**Comment by lmammino** [comment]
It's all your merit 😉
