### ISSUE TITLE
TypeError while launching it

### ISSUE THREAD

**Issue by russellhoff** [lmammino/godaddy-dns#23]
Hi!
I'm sorry to bother you again. I just installed the latest version and created a config file like the following:
```
{
  "apiKey": "****",
  "secret": "****",
  "domain": "mydomain.com",
  "records": [
    {"type": "A", "name": "@", "ttl": 600}
  ]
}
```

Afterwards, I type `godaddy-dns -c mydomain.com-config.json` and an exception is thrown:
```
[Wed Nov 29 2017 19:30:57 GMT+0100 (CET)] TypeError: Promise.resolve(...).each is not a function
```

PS: My godaddy keys are production's.

Thank you again!

**Comment by russellhoff** [comment]
@lmammino have you had the chance to review this issue? I can help. Thank you!

**Comment by lmammino** [comment]
Hey @russellhoff, i had a quick look and I think there's actually a bug introduced in one of the latest release. I am going to take care of fixing this asap and introduce a unit test suite to avoid this will happen again in the future?

**Comment by russellhoff** [comment]
Okay, thank you!

**Comment by lmammino** [comment]
@russellhoff, version 1.2.0 just landed. It should fix the issue!

Let me know if it works for you

**Comment by russellhoff** [comment]
I'll try it later and keep you informed ;)

**Comment by russellhoff** [comment]
It's working, thank you!

**Comment by lmammino** [comment]
Glad to hear! I Look forward to getting your feedback. Also feel more than welcome to keep contributing the project

**Comment by russellhoff** [comment]
Sure! The tool works as expected and no enhancements come to my mind :)
