### ISSUE TITLE
cronjob not working.

### ISSUE THREAD

**Issue by ovidiulaz7** [lmammino/godaddy-dns#34]
Log file output:

/bin/sh: 1: godaddy-dns: not found

which godaddy-dns
/usr/local/bin/godaddy-dns

cronjob:

*/5 * * * * godaddy-dns > /var/log/godaddy-dns.log 2>&1

cronjob installed under root user.

any ideas? 

if I type 

godaddy-dns
[Tue Jul 03 2018 12:19:10 GMT+0300 (EEST)] Current ip and last ip match. No update neccessary.

Thanks.

**Comment by lmammino** [comment]
Is NPM bin path exposed to your root user?

**Comment by lmammino** [comment]
if not you can try to use the full binary path in your cron definition. Something like:

```
*/5 * * * * /full/path/bin/godaddy-dns > /var/log/godaddy-dns.log 2>&1
```

**Comment by ovidiulaz7** [comment]
If I run it in terminal just using 'godaddy-dns' with the root user it runs, so I think the npm bin path is exposed to root user.. 

I already tried with full path too:

*/1 * * * * /usr/local/bin/godaddy-dns > /var/log/godaddy-dns.log 2>&1

log output file:

/usr/bin/env: node: No such file or directory

**Comment by lmammino** [comment]
Then it seems node to be missing in your cron user...

**Comment by ovidiulaz7** [comment]
which node
/usr/local/bin/node

node --version
v6.9.2

**Comment by lmammino** [comment]
Hey sorry for the delay, i hope you already figured it out but to me it seems that you are either missing `node` or `/usr/bin/env` for some reason is not present in your machine.

The following approach might work even though it might not be the cleanest:

```
*/1 * * * * /usr/local/bin/node /usr/local/bin/godaddy-dns > /var/log/godaddy-dns.log 2>&1
```

**Comment by ovidiulaz7** [comment]
it works indeed. 

thanks you for your time. :)

**Comment by lmammino** [comment]
Glad it works :)
