### ISSUE TITLE
Duplicating DNS records

### ISSUE THREAD

**Issue by bozzzi** [lmammino/godaddy-dns#8]
Hi,

Thx for great work.

I'm updating host with "godaddy-dns -c config.json -i last.ip".

Config.json: 

{
  "apiKey": "xxxxxxxxxxxxxxxxxxxxx",
  "secret": "yyyyyyyyyyyyyyyyyyyyyy",
  "domain": "domain.com",
  "records": [{"type": "A", "name": "subdomain", "ttl": 600}]
}

After few updates, I noticed that I have many (same as update times) subdomains in godaddy DNS manager. I thought that expected behaviour should be ONE subdomain with last IP, NOT 10 same subdomains with different IPs.

GoDaddy DNS Management excerpt:

Type	   Name	        Value	        TTL	Actions
A	  @	                0.0.0.0	        1/2 Hour	Edit
A	subdomain	00.00.00.00	1 Hour	Edit
A	subdomain	00.00.00.00	1 Hour	Edit
A	subdomain	00.00.00.00	1 Hour	Edit
A	subdomain	00.00.00.00	1 Hour	Edit
A	subdomain	00.00.00.00	1 Hour	Edit
A	subdomain	00.00.00.00	1 Hour	Edit
A	subdomain	00.00.00.00	1 Hour	Edit
A	subdomain	00.00.00.00	1 Hour	Edit
A	subdomain	00.00.00.00	1 Hour	Edit
NS	@	ns11.domaincontrol.com	1 Hour
NS	@	ns12.domaincontrol.com	1 Hour

Am I missing something obvious???

Thank you

**Comment by lmammino** [comment]
Hello @bozzzi ,
thank you for submitting this issue. This looks weird but I am probably using the wrong api call on the GoDaddy side. I'll have a look at it as soon as possible.

**Comment by lmammino** [comment]
@bozzzi, sorry for the delay, I didn't have much time to spend on this lately.

By quickly reviewing the [GoDaddy API documentation ](https://developer.godaddy.com/doc#!/_v1_domains/recordReplace) it seems that the right behaviour (replacing all the A records) is obtained with the *PUT* method (rather than *PATCH*).

I will be able to test this thoroughly probably on the weekend, but if you want to try on your own you just need to change the HTTP method to PUT in [godaddy-dns.j line 87](https://github.com/lmammino/godaddy-dns/blob/master/godaddy-dns.js#L87).

I'll keep you posted.

**Comment by bozzzi** [comment]
Thank you for info.

I'll try a little bit later and will inform you.

**Comment by lmammino** [comment]
Sorry for the very late reply,
I just found out a solution:

API URL should be `https://api.godaddy.com/v1/domains/{domain}/records/A/{subdomain}` and the request method should be `PUT`.

I'll try to update the code during this or the next weekend.

**Comment by bozzzi** [comment]
Great news.

Thanks

**Comment by bruce6666** [comment]
Hi, I am new to Node.js and unable to get the value of the name of he record but I modified the script with the method PUT and the URL with name of the record directly.
URL is now https://api.godaddy.com/v1/domains/${config.domain}/records/A/%40

You need to put %40 in the URL for '@'. Maybe you can add a condition in the script for that.

Thanks!

**Comment by lmammino** [comment]
Thanks for the tip @bruce6666!

I will try to update the script as soon as possible (I have been tremendously busy lately 😭)
